import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../domain/entities/forensic_case.dart';
import '../../domain/repositories/forensic_case_repository.dart';
import '../providers/forensic_case_providers.dart';

/// Cases State
class CasesState {
  final bool isLoading;
  final List<ForensicCase> cases;
  final String? errorMessage;
  
  const CasesState({
    this.isLoading = false,
    this.cases = const [],
    this.errorMessage,
  });
  
  CasesState copyWith({
    bool? isLoading,
    List<ForensicCase>? cases,
    String? errorMessage,
  }) {
    return CasesState(
      isLoading: isLoading ?? this.isLoading,
      cases: cases ?? this.cases,
      errorMessage: errorMessage,
    );
  }
}

/// Forensic Case Controller
class ForensicCaseController extends StateNotifier<CasesState> {
  final ForensicCaseRepository repository;
  
  ForensicCaseController(this.repository) : super(const CasesState());
  
  /// Load all cases
  Future<void> loadCases() async {
    state = state.copyWith(isLoading: true, errorMessage: null);
    
    final result = await repository.getCases();
    
    result.fold(
      (failure) {
        state = state.copyWith(
          isLoading: false,
          errorMessage: failure.message,
        );
      },
      (cases) {
        state = state.copyWith(
          isLoading: false,
          cases: cases,
          errorMessage: null,
        );
      },
    );
  }
  
  /// Load cases by status
  Future<void> loadCasesByStatus(CaseStatus status) async {
    state = state.copyWith(isLoading: true, errorMessage: null);
    
    final result = await repository.getCasesByStatus(status);
    
    result.fold(
      (failure) {
        state = state.copyWith(
          isLoading: false,
          errorMessage: failure.message,
        );
      },
      (cases) {
        state = state.copyWith(
          isLoading: false,
          cases: cases,
          errorMessage: null,
        );
      },
    );
  }
  
  /// Create new case
  Future<bool> createCase({
    required String title,
    required String description,
    required CasePriority priority,
    required List<String> tags,
    String? assignedTo,
    String? assignedToEmail,
  }) async {
    state = state.copyWith(isLoading: true, errorMessage: null);
    
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      state = state.copyWith(
        isLoading: false,
        errorMessage: 'User not authenticated',
      );
      return false;
    }
    
    final now = DateTime.now();
    final newCase = ForensicCase(
      caseId: '', // Will be generated by datasource
      title: title,
      description: description,
      createdBy: user.uid,
      createdByEmail: user.email ?? '',
      assignedTo: assignedTo,
      assignedToEmail: assignedToEmail,
      status: CaseStatus.open,
      priority: priority,
      evidenceCount: 0,
      tags: tags,
      createdAt: now,
      updatedAt: now,
      timeline: [
        TimelineEvent(
          action: 'created',
          userId: user.uid,
          timestamp: now,
          details: 'Case created',
        ),
      ],
    );
    
    final result = await repository.createCase(newCase);
    
    return result.fold(
      (failure) {
        state = state.copyWith(
          isLoading: false,
          errorMessage: failure.message,
        );
        return false;
      },
      (caseId) {
        // Reload cases after creation
        loadCases();
        return true;
      },
    );
  }
  
  /// Update case
  Future<bool> updateCase(ForensicCase updatedCase) async {
    state = state.copyWith(isLoading: true, errorMessage: null);
    
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      state = state.copyWith(
        isLoading: false,
        errorMessage: 'User not authenticated',
      );
      return false;
    }
    
    // Add timeline event
    final caseWithTimeline = updatedCase.copyWith(
      updatedAt: DateTime.now(),
      timeline: [
        ...updatedCase.timeline,
        TimelineEvent(
          action: 'updated',
          userId: user.uid,
          timestamp: DateTime.now(),
          details: 'Case updated',
        ),
      ],
    );
    
    final result = await repository.updateCase(caseWithTimeline);
    
    return result.fold(
      (failure) {
        state = state.copyWith(
          isLoading: false,
          errorMessage: failure.message,
        );
        return false;
      },
      (_) {
        // Reload cases after update
        loadCases();
        return true;
      },
    );
  }
  
  /// Delete case
  Future<bool> deleteCase(String caseId) async {
    state = state.copyWith(isLoading: true, errorMessage: null);
    
    final result = await repository.deleteCase(caseId);
    
    return result.fold(
      (failure) {
        state = state.copyWith(
          isLoading: false,
          errorMessage: failure.message,
        );
        return false;
      },
      (_) {
        // Remove from local state
        final updatedCases = state.cases
            .where((c) => c.caseId != caseId)
            .toList();
        
        state = state.copyWith(
          isLoading: false,
          cases: updatedCases,
          errorMessage: null,
        );
        return true;
      },
    );
  }
  
  /// Clear error
  void clearError() {
    state = state.copyWith(errorMessage: null);
  }
}

/// Controller provider
final forensicCaseControllerProvider =
    StateNotifierProvider<ForensicCaseController, CasesState>((ref) {
  return ForensicCaseController(
    ref.watch(forensicCaseRepositoryProvider),
  );
});
